Test deployed server.

diff --git a/.github/workflows/build_test_tun_application.yml b/.github/workflows/build_test_tun_application.yml
--- a/.github/workflows/build_test_tun_application.yml
+++ b/.github/workflows/build_test_tun_application.yml
@@ -38,5 +38,16 @@ jobs:
       with:
         compose-file: "./docker/docker-compose.yml"
         
+    - name: Wait for server to start
+          run: |
+            while ! curl -s localhost:1321; do sleep 1; done
+
     - name: Test server
-      run: curl -f http://localhost:1321/health/ || exit 1
+      run: |
+        response=$(curl -s localhost:1321)
+        if [[ "$response" == *"expected response"* ]]; then
+          echo "Server test passed"
+        else
+          echo "Server test failed"
+          exit 1
+        fi
